DROP TABLE IF EXISTS news;

CREATE TABLE news (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(1000) NOT NULL,
  lang CHAR(2) NOT NULL DEFAULT 'zh',
  title VARCHAR(500) NOT NULL,
  summary TEXT,
  source VARCHAR(100),
  category VARCHAR(50),
  severity TINYINT UNSIGNED DEFAULT 1,
  published_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_published_at (published_at DESC),
  INDEX idx_category (category),
  INDEX idx_source (source),
  INDEX idx_severity (severity),
  INDEX idx_lang (lang),
  INDEX idx_created_at (created_at DESC),
  INDEX idx_url_lang (url(255), lang)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO news (url, lang, title, summary, source, category, severity, published_at) VALUES
-- 1 OpenAI layoffs
('https://example.com/1', 'zh', 'OpenAI裁员风暴：大规模裁减运营团队', '据多位知情人士透露，OpenAI本周裁减了运营和安全团队的数十名员工，这是该公司今年第二轮大规模裁员。', 'TechCrunch', '裁员', 5, '2026-05-30 08:30:00'),
('https://example.com/1', 'en', 'OpenAI Layoff Storm: Mass Cuts Hit Operations Team', 'Multiple sources reveal OpenAI laid off dozens of operations and safety team members this week, marking the company second major round of layoffs this year.', 'TechCrunch', 'Layoffs', 5, '2026-05-30 00:30:00'),

-- 2 Nvidia market cap
('https://example.com/2', 'zh', 'AI芯片需求骤降 英伟达单日市值蒸发3000亿', '受企业AI支出放缓影响，英伟达股价单日暴跌12%，市值蒸发超3000亿美元，创历史最大单日跌幅。', 'Reuters', '算力', 5, '2026-05-30 06:15:00'),
('https://example.com/2', 'en', 'AI Chip Demand Plummets: Nvidia Loses $300B in Single Day', 'Driven by slowing enterprise AI spending, Nvidia shares plunged 12% in a single day, wiping over $300 billion in market cap.', 'Reuters', 'Compute', 5, '2026-05-29 22:15:00'),

-- 3 Gemini hallucination
('https://example.com/3', 'zh', '谷歌Gemini被曝严重幻觉问题 多家企业客户流失', '谷歌最新大模型Gemini在企业部署中频繁出现事实性错误，已导致至少3家财富500强客户转向竞争对手。', 'The Verge', '安全', 4, '2026-05-29 22:00:00'),
('https://example.com/3', 'en', 'Google Gemini Exposed for Severe Hallucination Issues, Multiple Clients Lost', 'Google latest large model Gemini frequently produces factual errors in enterprise deployments, causing at least 3 Fortune 500 clients to switch to competitors.', 'The Verge', 'Safety', 4, '2026-05-29 14:00:00'),

-- 4 EU AI Act
('https://example.com/4', 'zh', '欧盟通过最严AI监管法案 违者最高罚全球营收6%', '欧洲议会以压倒性多数通过AI法案修正案，将生成式AI纳入最高风险等级监管，违规企业面临全球营收6%的罚款。', 'Financial Times', '监管', 4, '2026-05-29 18:45:00'),
('https://example.com/4', 'en', 'EU Passes Strictest AI Regulation: Violators Face Up to 6% Global Revenue Fine', 'The European Parliament overwhelmingly passed AI Act amendments, classifying generative AI under the highest risk tier.', 'Financial Times', 'Regulation', 4, '2026-05-29 10:45:00'),

-- 5 Cruise shutdown
('https://example.com/5', 'zh', '自动驾驶公司Cruise宣布倒闭 2000人失业', '通用汽车旗下自动驾驶子公司Cruise正式宣布停止运营，约2000名员工被裁，自动驾驶商业化再遭重创。', 'Bloomberg', '裁员', 5, '2026-05-29 14:20:00'),
('https://example.com/5', 'en', 'Self-Driving Company Cruise Shuts Down, 2,000 Jobs Lost', 'GM autonomous driving subsidiary Cruise officially ceased operations, laying off approximately 2,000 employees.', 'Bloomberg', 'Layoffs', 5, '2026-05-29 06:20:00'),

-- 6 AI code security
('https://example.com/6', 'zh', 'AI生成代码致重大安全漏洞 多家科技公司紧急修复', '安全研究人员发现，由AI编程助手生成的代码中存在系统性安全缺陷，影响范围涉及金融和医疗领域。', 'Wired', '安全', 4, '2026-05-29 10:00:00'),
('https://example.com/6', 'en', 'AI-Generated Code Causes Major Security Vulnerabilities, Tech Companies Scramble', 'Security researchers discovered systematic security flaws in code generated by AI coding assistants, affecting financial and healthcare sectors.', 'Wired', 'Safety', 4, '2026-05-29 02:00:00'),

-- 7 Anthropic lawsuit
('https://example.com/7', 'zh', 'Anthropic被诉侵犯版权 训练数据未经授权', '多位作家和出版商联合起诉Anthropic，指控其未经授权使用受版权保护的书籍训练Claude模型。', 'NYTimes', '诉讼', 3, '2026-05-28 20:30:00'),
('https://example.com/7', 'en', 'Anthropic Sued for Copyright Infringement Over Unauthorized Training Data', 'Multiple authors and publishers jointly sued Anthropic, alleging unauthorized use of copyrighted books to train the Claude model.', 'NYTimes', 'Lawsuit', 3, '2026-05-28 12:30:00'),

-- 8 Data center power
('https://example.com/8', 'zh', 'AI数据中心用电量飙升 多地电网告急', '随着AI算力需求暴增，美国多个州的数据中心用电量已超过电网承载能力，部分地区面临停电风险。', 'WSJ', '算力', 3, '2026-05-28 15:00:00'),
('https://example.com/8', 'en', 'AI Data Center Power Consumption Surges, Multiple Grids at Capacity', 'With exploding AI compute demand, data center power consumption in several US states has exceeded grid capacity, with some regions facing blackout risks.', 'WSJ', 'Compute', 3, '2026-05-28 07:00:00'),

-- 9 Stability AI
('https://example.com/9', 'zh', 'Stability AI资金链断裂 CEO确认寻求出售', 'AI图像生成公司Stability AI确认已无法维持正常运营，CEO表示正在与多方洽谈出售事宜。', 'TechCrunch', '裁员', 4, '2026-05-28 09:45:00'),
('https://example.com/9', 'en', 'Stability AI Runs Out of Cash, CEO Confirms Seeking Buyer', 'AI image generation company Stability AI confirmed it can no longer sustain normal operations, with the CEO stating talks are underway for a potential sale.', 'TechCrunch', 'Layoffs', 4, '2026-05-28 01:45:00'),

-- 10 AI hiring bias
('https://example.com/10', 'zh', 'AI面试系统被曝种族和性别歧视 多州立法禁止', '研究表明主流AI招聘系统对特定种族和性别存在系统性偏见，已有8个州立法禁止在招聘中使用AI筛选。', 'The Guardian', '监管', 3, '2026-05-27 16:30:00'),
('https://example.com/10', 'en', 'AI Interview System Exposed for Racial and Gender Bias, States Ban Use', 'Research shows mainstream AI hiring systems exhibit systematic bias against certain races and genders; 8 states have legislated bans on AI screening.', 'The Guardian', 'Regulation', 3, '2026-05-27 08:30:00'),

-- 11 Copilot returns
('https://example.com/11', 'zh', '微软Copilot企业版退货率超40% 用户称效果不及预期', '消息人士透露，微软Copilot for Enterprise的续费率不足60%，大量企业客户反馈AI助手实际效果远低于宣传。', 'The Information', '安全', 2, '2026-05-27 11:00:00'),
('https://example.com/11', 'en', 'Microsoft Copilot Enterprise Return Rate Exceeds 40%, Users Say Results Fall Short', 'Sources reveal Microsoft Copilot for Enterprise has a renewal rate below 60%, with many enterprise clients reporting the AI assistant actual performance falls short.', 'The Information', 'Safety', 2, '2026-05-27 03:00:00'),

-- 12 FDA AI medical
('https://example.com/12', 'zh', 'AI医疗诊断系统误诊率被瞒报 FDA介入调查', '内部举报人披露某AI医疗影像公司长期隐瞒产品误诊率数据，FDA已启动正式调查。', 'Stat News', '安全', 5, '2026-05-27 08:15:00'),
('https://example.com/12', 'en', 'AI Medical Diagnosis System Misdiagnosis Rate Covered Up, FDA Launches Investigation', 'A whistleblower disclosed that an AI medical imaging company long concealed its product misdiagnosis rate data; the FDA has launched a formal investigation.', 'Stat News', 'Safety', 5, '2026-05-27 00:15:00'),

-- 13 AI investment cooling
('https://example.com/13', 'zh', '全球AI投资降温 Q2融资额环比下降35%', '最新数据显示，2026年Q2全球AI领域融资额较上季度下降35%，创两年来新低，投资者对AI商业化前景趋于谨慎。', 'CB Insights', '算力', 3, '2026-05-26 14:00:00'),
('https://example.com/13', 'en', 'Global AI Investment Cools: Q2 Funding Drops 35% Quarter-over-Quarter', 'Latest data shows global AI funding in Q2 2026 fell 35% from the previous quarter, hitting a two-year low.', 'CB Insights', 'Compute', 3, '2026-05-26 06:00:00'),

-- 14 Meta Llama
('https://example.com/14', 'zh', 'Meta AI部门大规模重组 Llama团队核心成员离职', 'Meta对其AI研究部门进行大规模重组，Llama模型团队至少5名核心研究员已确认离职。', 'The Verge', '裁员', 3, '2026-05-26 10:30:00'),
('https://example.com/14', 'en', 'Meta AI Division Undergoes Major Restructuring, Llama Team Core Members Depart', 'Meta has undertaken a major restructuring of its AI research division, with at least 5 core researchers from the Llama model team confirmed to have left.', 'The Verge', 'Layoffs', 3, '2026-05-26 02:30:00'),

-- 15 Deepfakes
('https://example.com/15', 'zh', 'AI生成深度伪造视频激增 社交平台治理失效', '2026年上半年AI生成的深度伪造视频数量同比增长800%，各大社交平台承认现有检测手段已无法有效识别。', 'MIT Tech Review', '安全', 4, '2026-05-25 19:00:00'),
('https://example.com/15', 'en', 'AI-Generated Deepfake Videos Surge 800%, Social Platforms Struggle to Detect', 'AI-generated deepfake videos increased 800% year-over-year in H1 2026; major social platforms admit existing detection tools can no longer effectively identify them.', 'MIT Tech Review', 'Safety', 4, '2026-05-25 11:00:00');
